# # Freezed高速化用、指定見直し必要。。。
# targets:
#   $default:
#     builders:
#       freezed:
#         generate_for:
#           include:
#             - lib/**/*state.dart
#             - lib/model/entities/**/*.dart
#             # - lib/model/firestore/**/*.dart
#       json_serializable:
#         generate_for:
#           include:
#             - lib/**/*state.dart
#             - lib/model/entities/**/*.dart
#             # - lib/model/firestore/**/*.dart
#         options:
#           any_map: true
#           explicit_to_json: true