name: newslist
description: newslist.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
  # sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"
dependencies:
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.1.0
  connectivity_plus: ^2.3.0
  dart_style: ^2.0.3
  device_info_plus: ^3.2.3
  drift: ^1.7.1
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  flutter_lints: ^1.0.4
  flutter_tts: ^3.3.3
  freezed_annotation: null
  go_router: ^3.0.7
  hooks_riverpod: ^1.0.3
  http: null
  image_picker: ^0.8.1+3
  intl: ^0.17.0
  package_info: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.8
  permission_handler: ^10.0.0
  platform: ^3.1.0
  platform_device_id: ^1.0.1
  shared_preferences: ^2.0.5
  simple_logger: null
  sqlite3_flutter_libs: ^0.5.8
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: null
  drift_dev: ^1.7.0
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2
  image_test_utils:
    git:
      url: https://github.com/mono0926/image_test_utils.git
      ref: add-compressionState
  json_serializable: null
  mockito: null
  pedantic_mono: null

flutter:
  uses-material-design: true
  generate: true #自動生成フラグの有効化
  assets:
    - assets/
    - assets/ic_app.png

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/ic_app.png"
  adaptive_icon_foreground: "assets/ic_app.png"
  adaptive_icon_background: "#46B4EB"
